#!/usr/bin/with-contenv bash

if ! command -v git; then
    echo "**** Adding git to package install list ****"
    echo "git" >> /mod-repo-packages-to-install.list
else
    echo "**** git already installed, skipping ****"
fi
