#!/usr/bin/with-contenv bash

if [[ -f /usr/bin/apt ]]; then
    # Ubuntu
    cp /unrar6/unrar-ubuntu /usr/bin/unrar
elif [[ -f /sbin/apk ]]; then
    # Alpine
    cp /unrar6/unrar-alpine /usr/bin/unrar
else
    echo "*** This mod only supports Ubuntu and Alpine-based containers ***"
fi
