#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Exit if no installable packages are provided
if [[ -z "${INSTALL_PACKAGES+x}" ]] && [[ -z "${INSTALL_PIP_PACKAGES+x}" ]]; then
    echo "[pkg-install-init] **** No packages to install ****"
    exit 0
fi

if [[ -n "${INSTALL_PIP_PACKAGES}" ]] && [[ -f /usr/bin/apt ]]; then
    echo "\
        python3-dev \
        python3-pip" >> /mod-repo-packages-to-install.list
elif [[ -n "${INSTALL_PIP_PACKAGES}" ]] && [[ -f /sbin/apk ]]; then
    echo "\
        python3-dev \
        py3-pip" >> /mod-repo-packages-to-install.list
fi

# Split list of packages on delimiter '|'
IFS="|" read -r -a SPLIT_INSTALL_PACKAGES <<< "${INSTALL_PACKAGES}"
for PKG in "${SPLIT_INSTALL_PACKAGES[@]}"; do
    echo "[pkg-install-init] **** Adding ${PKG} to OS package install list ****"
    echo "${PKG}" >> /mod-repo-packages-to-install.list
done

IFS="|" read -r -a SPLIT_INSTALL_PIP_PACKAGES <<< "${INSTALL_PIP_PACKAGES}"
for PKG in "${SPLIT_INSTALL_PIP_PACKAGES[@]}"; do
    echo "[pkg-install-init] **** Adding ${PKG} to pip install list ****"
    echo "${PKG}" >> /mod-pip-packages-to-install.list
done
