#!/usr/bin/with-contenv bash

if [ -d /config/custom_components/hacs ]; then
  echo "**** HACS already installed, skipping ****"
else
  echo "**** Installing HACS ****"
  curl -o /tmp/hacs.zip \
    -fL "https://github.com/hacs/integration/releases/latest/download/hacs.zip"
  mkdir -p /config/custom_components/hacs
  unzip /tmp/hacs.zip -d /config/custom_components/hacs
  lsiown abc:abc /config/custom_components
  lsiown -R abc:abc /config/custom_components/hacs
  rm -rf /tmp/hacs.zip
fi
