#!/usr/bin/with-contenv bash

if [ -f "/mod-repo-packages-to-install.list" ]; then
    echo "**** Installing all mod packages ****"
    if [ -f /usr/bin/apt ]; then
        DEBIAN_FRONTEND="noninteractive"
        apt-get install -y \
            $(cat /mod-repo-packages-to-install.list)
    elif [ -f /usr/bin/apk ]; then
        apk add --no-cache \
            $(cat /mod-repo-packages-to-install.list)
    fi
else
    echo "**** No repo packages to install, skipping ****"
fi

if [ -f "/mod-pip-packages-to-install.list" ]; then
    echo "**** Installing all pip packages ****"
    python3 -m pip install -U pip wheel setuptools
    if [ -f /usr/bin/apt ]; then
        PIP_ARGS="-f https://wheel-index.linuxserver.io/ubuntu/"
    elif [ -f /usr/bin/apk ]; then
        ALPINE_VER=$(cat /etc/apk/repositories | grep main | sed 's|.*alpine/v||' | sed 's|/main.*||')
        if [ "${ALPINE_VER}" = "3.14" ]; then
            PIP_ARGS="-f https://wheel-index.linuxserver.io/alpine/"
        else
            PIP_ARGS="-f https://wheel-index.linuxserver.io/alpine-${ALPINE_VER}/"
        fi
    fi
    python3 -m pip install ${PIP_ARGS} \
        $(cat /mod-pip-packages-to-install.list)
fi

rm -rf \
    /mod-repo-packages-to-install.list \
    /mod-pip-packages-to-install.list
