#!/usr/bin/with-contenv bash

NVM_DIR="$HOME/.nvm"

echo "**** installing nvm ****"
if [ ! -s "$NVM_DIR/nvm.sh" ]; then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

  echo "**** loading nvm ****"
  source "$NVM_DIR/nvm.sh"

  echo "**** installing the latest release ****"
  nvm install node
else
  echo "**** nvm already installed, skipping ****"
fi
