#!/usr/bin/with-contenv bash

if ! pip list 2> /dev/null | grep -q "pillow-heif" || ! pip list 2> /dev/null | grep -q "hexhamming" || ! pip list 2> /dev/null | grep -q "PyWavelets"; then
    echo "**** Adding pillow-heif, hexhamming, pywavelets and their deps to package install lists ****"
    echo "\
        ffmpeg \
        imagemagick \
        supervisor" >> /mod-repo-packages-to-install.list
    if [ $(arch) = "x86_64" ]; then
        echo "scipy" >> /mod-pip-packages-to-install.list
    fi
    echo "\
        asn1crypto \
        cryptography \
        hexhamming \
        numpy \
        pillow \
        pillow-heif \
        pynacl \
        pywavelets" >> /mod-pip-packages-to-install.list
else
    echo "**** pillow-heif, hexhamming and pywavelets already installed, skipping ****"
fi
