#!/usr/bin/with-contenv bash

if [ ! -S /var/run/docker.sock ] && [ -z "$DOCKER_HOST" ]; then
    echo "**** Docker mod not set up properly, skipping SWAG auto-proxy ****"
    exit 0
fi

rm -rf /etc/nginx/http.d/auto-proxy*.conf /config/nginx/proxy-confs/auto-proxy*.conf
sed -i 's|#include /etc/nginx/http.d|include /etc/nginx/http.d|' /config/nginx/nginx.conf
cp /defaults/auto-proxy-readme /etc/nginx/http.d/auto-proxy-readme
rm -rf /auto-proxy
mkdir /auto-proxy

if ! grep -q "/app/docker-wrap.sh" /config/crontabs/root; then
    echo "*       *       *       *       *       /app/docker-wrap.sh" >> /config/crontabs/root
    cp /config/crontabs/root /etc/crontabs/root
fi

FIRST_RUN=true
. /app/docker-wrap.sh
