#!/usr/bin/with-contenv bash

# This is an install script that is designed to run after init-mods-package-install
# so it can take advantage of packages installed
# init-mods-end depends on this script so that later init and services wait until this script exits

 curl -o \
    /tmp/biftool_linux.zip -L \
    "https://github.com/rokudev/samples/raw/master/utilities/bif%20tool/biftool_linux.zip" && \
  cd /tmp && \
  unzip biftool_linux.zip -d /usr/bin && \