#!/usr/bin/with-contenv bash

if [[ ! -f /usr/bin/biftool ]]; then
  echo "**** Installing BIF Tool ****"
  curl -fL \
    "https://github.com/rokudev/samples/raw/master/utilities/bif%20tool/biftool_linux.zip" \
    -o /tmp/biftool_linux.zip && \
  cd /tmp && \
  unzip -uo biftool_linux.zip -d /usr/bin
else
  echo "**** BIF Tool already installed ****"
fi
