#!/usr/bin/with-contenv bash

if [ ! -f "/etc/apt/sources.list.d/ros2.list" ]; then
    echo "**** Adding ROS2 packages to install list ****"
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

    echo "ros-humble-ros-base ros-dev-tools" >> /mod-repo-packages-to-install.list

    if ! grep -q '/opt/ros/humble/setup.bash' /config/.bashrc; then
        echo "**** Automatically sourcing ROS2 ****"
        printf "\n# Automatically source ROS2 humble\nsource /opt/ros/humble/setup.bash" >> /config/.bashrc
    fi
else
    echo "**** ROS2 packages already installed, skipping ****"
fi