#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "" >/config/nginx/cf_real-ip.conf

curl -s "https://api.cloudflare.com/client/v4/ips" | jq -r '.result.ipv4_cidrs[]' | while IFS= read -r line; do
    echo "set_real_ip_from ${line};" >>/config/nginx/cf_real-ip.conf
done

curl -s "https://api.cloudflare.com/client/v4/ips" | jq -r '.result.ipv6_cidrs[]' | while IFS= read -r line; do
    echo "set_real_ip_from ${line};" >>/config/nginx/cf_real-ip.conf
done

ip route | grep -v default | awk '{print $1}' | while IFS= read -r line; do
    echo "set_real_ip_from ${line};" >>/config/nginx/cf_real-ip.conf
done

lsiown abc:abc /config/nginx/cf_real-ip.conf
