#!/usr/bin/with-contenv bash
echo  "_ _ _ "
echo  "| | | |"
echo  "| | | | The f2b to discord mod is deprecated"
echo  "|_|_|_|"
echo  "(_|_|_)"
        

if ! pip list 2>&1 | grep -q "requests"; then
  echo '------------------------------------------------------------------------'
  echo '| Adding required modules for swag-f2bdiscord deprecation message'
  echo '------------------------------------------------------------------------'
  echo "requests" >> /mod-pip-packages-to-install.list
fi

if [ ! -f /config/fail2ban/Fail2Ban.py.orig ] && [ -f /config/fail2ban/Fail2Ban.py ]; then
  mv /config/fail2ban/Fail2Ban.py /config/fail2ban/Fail2Ban.py.orig
fi

if [ ! -f /config/fail2ban/Fail2Ban.py ]; then
  cp /AwesomeFolder/Fail2Ban.py /config/fail2ban/
  chmod +x /config/fail2ban/Fail2Ban.py
fi

