#!/usr/bin/with-contenv bash

echo "Applying the swag-ondemand mod..."

if [ ! -S /var/run/docker.sock ] && [ -z "$DOCKER_HOST" ]; then
    echo "**** Docker not set up properly, skipping swag-ondemand ****"
    exit 0
fi

for pkg in $(cat /app/ondemand/requirements.txt); do
    echo "**** Checking if $pkg are already installed ****"
    if ! pip list 2>&1 | grep -iq "$pkg"; then
        echo "**** Adding $pkg to package install lists ****"
        echo "\
            $pkg" >> /mod-pip-packages-to-install.list
    else
        echo "**** $pkg already installed, skipping ****"
    fi
done

if [ ! -f /config/nginx/ondemand.conf ]; then
    cp /defaults/ondemand.conf /config/nginx/ondemand.conf
    lsiown -R abc:abc /config/nginx/ondemand.conf
fi

echo "Applied the swag-ondemand mod"
