#!/usr/bin/with-contenv bash

set -e

ARCH=$(uname -m)
if [[ "${ARCH}" = "armv7l" ]]; then
  echo "**** The docker mods no longer support arm32v7/armhf per https://info.linuxserver.io/issues/2023-07-01-armhf/ ****"
  exit 0
fi

if ! dpkg -l | grep build-essential >/dev/null; then
  echo "**** adding build-essential to install list ****"
  echo "build-essential" >> /mod-repo-packages-to-install.list
else
  echo "**** build-essential already installed ****"
fi

if [[ -f /rust-bins/rust.tar.gz ]]; then
  echo "**** unpacking rust tar ****"
  tar -xzf /rust-bins/rust.tar.gz -C /rust-bins --strip-components=1
  echo "**** installing rust ****"
  /rust-bins/install.sh
  rm -rf /rust-bins/rust.tar.gz
else
  echo "**** latest rust is already installed ****"
fi
