#!/usr/bin/with-contenv bash

# This is an install script that is designed to run after init-mods-package-install
# so it can take advantage of packages installed
# init-mods-end depends on this script so that later init and services wait until this script exits

if [ -d /config/.rbenv ]; then
    echo 'rbenv already cloned, skipping'
else
    echo 'Cloning rbenv repo'
    git clone https://github.com/rbenv/rbenv.git /config/.rbenv
fi

if [ -d /config/.rbenv/plugins/ruby-build ]; then
    echo 'ruby-build plugin already cloned, skipping'

    # On a docker start, even if this folder exists, we need to own it first for git to be able to pull
    echo 'Setting permissions for ~/.rbenv'
    lsiown -R abc:abc \
        /config/.rbenv

    echo 'Upgrading ruby-build plugin'
    git -C /config/.rbenv/plugins/ruby-build pull
else
    echo 'Cloning ruby-build plugin repo'
    git clone https://github.com/rbenv/ruby-build.git /config/.rbenv/plugins/ruby-build
fi

# This will add `eval "$(~/.rbenv/bin/rbenv init - --no-rehash bash)"` to the ~/.bashrc or ~/.bash_profile file
echo 'Initializing rbenv for bash'
/config/.rbenv/bin/rbenv init

if ! command -v zsh >/dev/null 2>&1; then
    echo "**** zsh not installed, skipping shell completions setup ****"
else
    # This will add `eval "$(~/.rbenv/bin/rbenv init - --no-rehash zsh)"` to the ~/.zshrc file
    echo 'Initializing rbenv for zsh'
    /config/.rbenv/bin/rbenv init zsh

    if [ -f /config/.zshrc ]; then
        if ! grep -q 'FPATH=~/.rbenv/completions:"$FPATH"' /config/.zshrc; then
            echo 'Adding shell completions to zsh for rbenv'

            echo '' >> /config/.zshrc
            echo '# For rbenv shell completions' >> /config/.zshrc
            echo 'FPATH=~/.rbenv/completions:"$FPATH"' >> /config/.zshrc
            echo 'autoload -U compinit' >> /config/.zshrc
            echo 'compinit' >> /config/.zshrc
        else
            echo 'rbenv shell completions already exist in zsh, skipping'
        fi
    else
        echo '/config/.zshrc not found, creating one with the shell completions'

        echo '' >> /config/.zshrc
        echo '# For rbenv shell completions' >> /config/.zshrc
        echo 'FPATH=~/.rbenv/completions:"$FPATH"' >> /config/.zshrc
        echo 'autoload -U compinit' >> /config/.zshrc
        echo 'compinit' >> /config/.zshrc
    fi
fi

echo 'Setting permissions for ~/.rbenv'
lsiown -R abc:abc \
    /config/.rbenv
