#!/usr/bin/with-contenv bash

# This is an install script that is designed to run after init-mods-package-install
# so it can take advantage of packages installed
# init-mods-end depends on this script so that later init and services wait until this script exits

if [ -d ~/.rbenv ]; then
    echo 'rbenv already cloned, skipping'
else
    echo 'Cloning rbenv repo'
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
fi

if [ -d ~/.rbenv/plugins/ruby-build ]; then
    echo 'ruby-build plugin already cloned, skipping'

    echo 'Upgrading ruby-build plugin'
    git -C ~/.rbenv/plugins/ruby-build pull
else
    echo 'Cloning ruby-build plugin repo'
    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
fi

# This will add `eval "$(~/.rbenv/bin/rbenv init - --no-rehash bash)"` to the ~/.bashrc or ~/.bash_profile file
echo 'Initializing rbenv for bash'
~/.rbenv/bin/rbenv init

if ! command -v zsh >/dev/null 2>&1; then
    echo "**** zsh not installed, skipping shell completions setup ****"
else
    # This will add `eval "$(~/.rbenv/bin/rbenv init - --no-rehash zsh)"` to the ~/.zshrc file
    echo 'Initializing rbenv for zsh'
    ~/.rbenv/bin/rbenv init zsh

    if [ -f ~/.zshrc ]; then
        if ! grep -q 'FPATH=~/.rbenv/completions:"$FPATH"' ~/.zshrc; then
            echo 'Adding shell completions to zsh for rbenv'

            echo '' >> ~/.zshrc
            echo '# For rbenv shell completions' >> ~/.zshrc
            echo 'FPATH=~/.rbenv/completions:"$FPATH"' >> ~/.zshrc
            echo 'autoload -U compinit' >> ~/.zshrc
            echo 'compinit' >> ~/.zshrc
        else
            echo 'rbenv shell completions already exist in zsh, skipping'
        fi
    else
        echo '~/.zshrc not found, creating one with the shell completions'

        echo '' >> ~/.zshrc
        echo '# For rbenv shell completions' >> ~/.zshrc
        echo 'FPATH=~/.rbenv/completions:"$FPATH"' >> ~/.zshrc
        echo 'autoload -U compinit' >> ~/.zshrc
        echo 'compinit' >> ~/.zshrc
    fi
fi

echo 'Setting permissions for ~/.rbenv'
lsiown -R abc:abc \
    /config/.rbenv
