#!/usr/bin/with-contenv bash

if [ -f "/etc/services.d/openvscode-server/run" ]; then
    echo "**** adding --cert and --cert-key parameters to openvscode-server startup ****"
    sed -i 's/\/app\/openvscode-server\/bin\/openvscode-server \\/\/app\/openvscode-server\/bin\/openvscode-server \\\n            --cert ${SSL_CERT_PATH} \\\n            --cert-key ${SSL_KEY_PATH} \\/g' /etc/services.d/openvscode-server/run
elif [ -f "/etc/s6-overlay/s6-rc.d/svc-openvscode-server/run" ]; then
    echo "**** adding --cert and --cert-key parameters to openvscode-server startup ****"
    sed -i 's/\/app\/openvscode-server\/bin\/openvscode-server \\/\/app\/openvscode-server\/bin\/openvscode-server \\\n            --cert ${SSL_CERT_PATH} \\\n            --cert-key ${SSL_KEY_PATH} \\/g' /etc/s6-overlay/s6-rc.d/svc-openvscode-server/run
elif [ -f "/etc/services.d/code-server/run" ]; then
    echo "**** adding --cert and --cert-key parameters to code-server startup ****"
    sed -i 's/\/bin\/code-server \\/\/bin\/code-server \\\n            --cert ${SSL_CERT_PATH} \\\n            --cert-key ${SSL_KEY_PATH} \\/g' /etc/services.d/code-server/run
elif [ -f "/etc/s6-overlay/s6-rc.d/svc-code-server/run" ]; then
    echo "**** adding --cert and --cert-key parameters to code-server startup ****"
    sed -i 's/\/bin\/code-server \\/\/bin\/code-server \\\n            --cert ${SSL_CERT_PATH} \\\n            --cert-key ${SSL_KEY_PATH} \\/g' /etc/s6-overlay/s6-rc.d/svc-code-server/run
fi
