#!/usr/bin/with-contenv bash

if [ -n "$OCRLANG" ]; then
    echo "**** OCRLANG variable is set, processing the language packages ****"
    for i in $(echo "$OCRLANG" | tr "," " "); do
        if apt-cache show tesseract-ocr-"${i}" > /dev/null 2>&1; then
            if ! dpkg -s tesseract-ocr-"${i}" >/dev/null 2>&1; then
                echo "**** Adding tesseract-ocr-${i} to package install list ****"
                echo "tesseract-ocr-${i}" >> /mod-repo-packages-to-install.list
            else
                echo "**** tesseract-ocr-${i} is already installed, skipping ****"
            fi
        else
            echo "**** package tesseract-ocr-${i} not found in the repository, skipping ****"
        fi
    done
fi
