#!/usr/bin/with-contenv bash

## Ubuntu
if [ -f /usr/bin/apt ]; then
    for package in iputils-ping openssh-client wakeonlan; do
        if ! dpkg -s "${package}" >/dev/null 2>&1; then
            PACKAGES="${package} ${PACKAGES}"
        fi
    done
fi
# Alpine
if [ -f /sbin/apk ]; then
    if ! grep -qxF '@testing https://dl-cdn.alpinelinux.org/alpine/edge/testing' /etc/apk/repositories; then
        echo @testing https://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories
    fi
    for package in openssh wol@testing; do
        if ! apk info -e "${package}" >/dev/null 2>&1; then
            PACKAGES="${package} ${PACKAGES}"
        fi
    done
fi

if [ -n "${PACKAGES}" ]; then
    echo "${PACKAGES}" >> /mod-repo-packages-to-install.list
    echo click pyyaml >> /mod-pip-packages-to-install.list
    echo "**** Adding rffmpeg dependencies to package install list ****"
else
    echo "**** rffmpeg dependencies already installed, skipping ****"
fi
