#!/usr/bin/with-contenv bash

if ! dpkg -s fonts-dejavu >/dev/null; then
    echo "**** Adding firefox-fonts packages to install list ****"
    echo "\
        fonts-dejavu \
        fonts-noto-color-emoji \
        fonts-noto-cjk \
        fonts-croscore >> /mod-repo-packages-to-install.list
else
    echo "**** Firefox-fonts packages already installed, skipping ****"
fi
