#!/usr/bin/with-contenv bash

# This is an install script that is designed to run after init-mods-package-install
# so it can take advantage of packages installed
# init-mods-end depends on this script so that later init and services wait until this script exits

if ! command -v zsh >/dev/null 2>&1; then
    echo "**** zsh not installed, skipping alias setup ****"
else
    if [ -f ~/.zshrc ]; then
        if ! grep -q 'alias bat="batcat"' ~/.zshrc; then
            echo 'Adding alias to zsh for bat'
            echo 'alias bat="batcat"' >> ~/.zshrc
        else
            echo 'Alias already exists in zsh, skipping'
        fi
    else
        echo '~/.zshrc not found, creating one with the alias'
        echo 'alias bat="batcat"' > ~/.zshrc
    fi
fi

if ! command -v bash >/dev/null 2>&1; then
    echo "**** bash not installed, skipping alias setup ****"
else
    if [ -f ~/.bash_profile ]; then
        if ! grep -q 'alias bat="batcat"' ~/.bash_profile; then
            echo 'Adding alias to ~/.bash_profile for bat'
            echo 'alias bat="batcat"' >> ~/.bash_profile
        else
            echo 'Alias already exists in ~/.bash_profile, skipping'
        fi
    elif [ -f ~/.bashrc ]; then
        if ! grep -q 'alias bat="batcat"' ~/.bashrc; then
            echo 'Adding alias to ~/.bashrc for bat'
            echo 'alias bat="batcat"' >> ~/.bashrc
        else
            echo 'Alias already exists in ~/.bashrc, skipping'
        fi
    else
        echo '~/.bash_profile or ~/.bashrc not found, creating one with the alias'
        echo 'alias bat="batcat"' > ~/.bash_profile
    fi
fi

if [ -d ~/.bat-extras ]; then
    echo 'Bat-extras already installed, skipping'
else
    echo 'Installing bat-extras'
    git clone https://github.com/eth-p/bat-extras.git ~/.bat-extras
    cd ~/.bat-extras/src
    chmod +x ~/.bat-extras/src/*.sh
    ln -s ~/.bat-extras/src/*.sh /usr/local/bin
fi

lsiown -R abc:abc \
    /config/.bat-extras
