#!/usr/bin/with-contenv bash

if [ -n "${LOGS_TO_STDOUT}" ]; then
    IFS='|' read -ra PATH_ARRAY <<< "$LOGS_TO_STDOUT"
    echo "Executing: tail -F ${PATH_ARRAY[@]}"
    tail -F "${PATH_ARRAY[@]}"
else
    echo "**** Env var LOGS_TO_STDOUT is not set, sleeping ****"
fi
