#!/usr/bin/with-contenv bash

if [ -f /usr/bin/apt ]; then
    ## Ubuntu
    echo "\
        iptables \
        openssh-client \
        python3 \
        python3-pip" >> /mod-repo-packages-to-install.list
fi

if [ -f /sbin/apk ]; then
    # Alpine
    echo "\
        iptables \
        openssh \
        python3 \
        py3-pip" >> /mod-repo-packages-to-install.list
fi

echo "\
    sshuttle" >> /mod-pip-packages-to-install.list

chown -R root:root /root
chmod -R 600 /root/.ssh
