#!/usr/bin/with-contenv bash
# shellcheck shell=bash

for cron_user in abc root; do
    # make folders
    mkdir -p \
        /config/crontabs

    # if crontabs do not exist in config
    if [[ ! -f "/config/crontabs/${cron_user}" ]]; then
        # copy crontab from system
        if crontab -l -u "${cron_user}" >/dev/null; then
            crontab -l -u "${cron_user}" >"/config/crontabs/${cron_user}"
        fi

        if [[ -f "/defaults/crontabs/${cron_user}" ]]; then
            # if crontabs still do not exist in config (were not copied from system)
            # copy crontab from image defaults (using -n, do not overwrite an existing file)
            cp -n "/defaults/crontabs/${cron_user}" /config/crontabs/
        fi

        # if crontabs still do not exist in config (were not copied from system)
        # copy crontab from mod defaults (using -n, do not overwrite an existing file)
        cp -n "/defaults/crontabs-mod/${cron_user}" /config/crontabs/
    fi

    # set permissions and import user crontabs
    lsiown "${cron_user}":"${cron_user}" "/config/crontabs/${cron_user}"
    crontab -u "${cron_user}" "/config/crontabs/${cron_user}"
done
