#!/usr/bin/with-contenv bash

if [[ ! -f /usr/bin/apt ]]; then
cat <<-EOF
    ********************************************************
    ********************************************************
    *                                                      *
    *                         !!!!                         *
    *   universal-calibre mod is only supported on images  *
    *             using an Ubuntu base image.              *
    *                                                      *
    ********************************************************
    ********************************************************
EOF
exit 0
fi

export DEBIAN_FRONTEND="noninteractive"

if [[ ! -e /usr/bin/calibre-server ]]; then
    tar xf \
        /tmp/calibre.txz \
        -C /app/calibre
    rm /tmp/calibre.txz
    echo "Installing Calibre version $(cat /CALIBRE_RELEASE)"
    /app/calibre/calibre_postinstall
fi
