#!/usr/bin/with-contenv bash

# This is the init file used for adding os or pip packages to install lists.
# It takes advantage of the built-in init-mods-package-install init script that comes with the baseimages.
# If using this, we need to make sure we set this init as a dependency of init-mods-package-install so this one runs first
#!/usr/bin/with-contenv bash

if ! dpkg -s git >/dev/null 2>&1; then
    echo "**** Adding git to package install list ****"
    echo "git" >> /mod-repo-packages-to-install.list
else
    echo "**** git already installed, skipping ****"
fi

# List comes from: https://github.com/rbenv/ruby-build/wiki#ubuntudebianmint
echo "Adding the required packages of the build environment for rbenv ruby-build "
echo "\
        autoconf \
        build-essential \
        libffi-dev \
        libgmp-dev \
        libssl-dev \
        libyaml-dev \
        rustc \
        zlib1g-dev" >> /mod-repo-packages-to-install.list
