#!/usr/bin/with-contenv bash

echo "*** AWSCLI Installer ***"
echo "Checking if awscli is installed"

if ! aws -v COMMAND &> /dev/null; then 
    echo "**** awscli not installed, adding to packages to be installed ****" 
    echo "awscli" >> /mod-pip-packages-to-install.list
    if ! pip3 -v COMMAND &> /dev/null; then
        echo "*** Pip not installed, adding to packages to be installed ****" 
        echo "python3 python3-pip" >> /mod-repo-packages-to-install.list
    fi
else
    echo "awscli already installed, skipping!"
fi