#!/usr/bin/with-contenv bash

echo "**** ensuring golang is in PATH ****"
if ! grep -q -E '.*/usr/local/go/bin.*' /var/run/s6/container_environment/PATH; then
    printf ':/usr/local/go/bin' >> /var/run/s6/container_environment/PATH
fi
if ! grep -q -E '.*/config/go/bin:.*' /var/run/s6/container_environment/PATH; then
    sed -i '1s|^|/config/go/bin:|' /var/run/s6/container_environment/PATH
fi

ARCH=$(uname -m)
if [ -f "/golang/golang_${ARCH}.tar.gz" ]; then
    echo "**** Installing golang ****"
    tar xzf "/golang/golang_${ARCH}.tar.gz" -C /usr/local
    rm -rf /golang

    echo "**** Adding gcc to package install list, to make CGO work ****"
    echo "gcc" >> /mod-repo-packages-to-install.list
else
    echo "**** Golang already installed, skipping ****"
fi
