#!/usr/bin/with-contenv bash

if ! dpkg -l | grep gnupg > /dev/null; then
    apt-get update && apt-get install -y gnupg
fi

if [ ! -f "/etc/apt/sources.list.d/r.list" ]; then
    echo "**** Adding r packages to install list ****"
    curl -s https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | apt-key add -
    source /etc/lsb-release
    echo "deb https://cloud.r-project.org/bin/linux/ubuntu ${DISTRIB_CODENAME}-cran40/" > /etc/apt/sources.list.d/r.list
    echo "\
        build-essential \
        r-base" >> /mod-repo-packages-to-install.list
else
    echo "**** r packages already installed, skipping ****"
fi
