#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ ! -f /usr/sbin/cron ] && [ -f /usr/bin/apt ]; then
    echo "**** Adding cron to package install list ****"
    echo "cron" >>/mod-repo-packages-to-install.list
else
    echo "**** cron package already installed, skipping ****"
fi
