#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if ! builtin command -v busybox >/dev/null; then
    echo "**** Adding busybox to package install list ****"
    echo "busybox" >>/mod-repo-packages-to-install.list
fi
if [[ -f /usr/bin/apt ]] && [[ ! -f /usr/sbin/cron ]]; then
    echo "**** Adding cron to package install list ****"
    echo "cron" >>/mod-repo-packages-to-install.list
fi
