#!/usr/bin/with-contenv bash

if ! python3 -m pip show netbox-plugin-dns >/dev/null 2>&1; then
    echo "**** Adding netbox-plugin-dns to package install list ****"
    echo "netbox-plugin-dns" >> /mod-pip-packages-to-install.list
else
    echo "**** netbox-plugin-dns already installed, skipping ****"
fi
