#!/usr/bin/with-contenv bash

if [ ! -f "/flutter/bin/flutter" ]; then
    echo "**** Installing Flutter ****"
    git clone https://github.com/flutter/flutter.git -b beta --depth 1 /flutter
    ln -s /flutter/bin/flutter /usr/bin/flutter
    flutter doctor
    flutter config --enable-web
    flutter config --no-analytics
else
    echo "**** Flutter already installed, skipping ****"
fi
