#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/crontabs

# if root crontabs do not exist in config
# copy root crontab from system
[[ ! -f /config/crontabs/root ]] && \
	cp /var/spool/cron/crontabs/root /config/crontabs/

# if root crontabs still do not exist in config (were not copied from system)
# copy root crontab from included defaults
[[ ! -f /config/crontabs/root ]] && \
	cp /defaults/crontabs-mod/root /config/crontabs/

# if abc crontabs do not exist in config
# copy abc crontab from system
[[ ! -f /config/crontabs/abc ]] && \
	cp /var/spool/cron/crontabs/abc /config/crontabs/

# if abc crontabs still do not exist in config (were not copied from system)
# copy abc crontab from included defaults
[[ ! -f /config/crontabs/abc ]] && \
	cp /defaults/crontabs-mod/abc /config/crontabs/

# import user crontabs
rm /var/spool/cron/crontabs/*
cp /config/crontabs/* /var/spool/cron/crontabs/

# determine if setup is needed for ubuntu
if [ ! -f /usr/sbin/cron ] && \
[ -f /usr/bin/apt ]; then
  # install cron
  apt-get update
  apt-get install --no-install-recommends -y \
    cron

  # import user crontabs
  crontab -u root /config/crontabs/root
  crontab -u abc /config/crontabs/abc

  # cleanup
  rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*
fi
