#!/usr/bin/with-contenv bash

echo '
**************************************************************************
**************************************************************************
**************************************************************************
****                                                                  ****
****                                                                  ****
****         letsencrypt-f2bdiscord mod has been deprecated           ****
****                                                                  ****
****                                                                  ****
****               Please use swag-f2bdiscord instead                 ****
****                                                                  ****
****                                                                  ****
**** https://github.com/linuxserver/docker-mods/tree/swag-f2bdiscord  ****
****                                                                  ****
****                                                                  ****
**************************************************************************
**************************************************************************
**************************************************************************
'


if [ ! -d /usr/lib/python3.8/site-packages/geoip2 ]; then
  echo '------------------------------------------------------------------------'
  echo '| Running installation of required modules for letsencrypt-f2bdiscord'
  echo '------------------------------------------------------------------------'
  pip3 install --no-cache-dir -U \
    requests \
    argparse \
    geoip2==3.0.0
fi

if [ ! -f /config/fail2ban/Fail2Ban.py ]; then
  cp /AwesomeFolder/Fail2Ban.py /config/fail2ban/
  chmod +x /config/fail2ban/Fail2Ban.py
fi

if [ ! -f /config/fail2ban/action.d/discordEmbed.conf ]; then
  cp /AwesomeFolder/discordEmbed.conf /config/fail2ban/action.d
fi
