#!/usr/bin/with-contenv bash

if [ ! -d /usr/lib/python3.8/site-packages/geoip2 ]; then
  echo '------------------------------------------------------------------------'
  echo '| Running installation of required modules for letsencrypt-f2bdiscord'
  echo '------------------------------------------------------------------------'
  pip3 install --no-cache-dir -U \
    requests \
    argparse \
    geoip2
fi

if [ ! -f /config/fail2ban/Fail2Ban.py ]; then
  cp /AwesomeFolder/Fail2Ban.py /config/fail2ban/
  chmod +x /config/fail2ban/Fail2Ban.py
fi

if [ ! -f /config/fail2ban/action.d/discordEmbed.conf ]; then
  cp /AwesomeFolder/discordEmbed.conf /config/fail2ban/action.d
fi