#!/usr/bin/with-contenv bash

if [ ! -f "/etc/apt/sources.list.d/amdgpu-focal.list" ]; then
    echo "**** Adding amdgpu repo ****"
    curl -sL --retry 3 https://repo.radeon.com/rocm/rocm.gpg.key | apt-key add -
    echo "deb [arch=amd64] https://repo.radeon.com/rocm/apt/5.4.1 ubuntu main" > /etc/apt/sources.list.d/amdgpu-focal.list
fi
