#!/usr/bin/with-contenv bash

echo "**** installing nodejs dev environment ****"
if ! dpkg -l | grep gnupg > /dev/null; then
    apt-get update && apt-get install -y gnupg
fi

source /etc/lsb-release
[[ ! -f "/etc/apt/sources.list.d/nodesource.list" ]] && \
    curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
    echo "deb https://deb.nodesource.com/node_18.x ${DISTRIB_CODENAME} main" \
        > /etc/apt/sources.list.d/nodesource.list
[[ ! -f "/etc/apt/sources.list.d/yarn.list" ]] && \
    curl -s https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo 'deb https://dl.yarnpkg.com/debian/ stable main' \
        > /etc/apt/sources.list.d/yarn.list
