#!/usr/bin/with-contenv bash

echo "**** installing nodejs dev environment ****"
if ! dpkg -l | grep gnupg > /dev/null; then
    apt-get update && apt-get install -y gnupg
fi

[[ ! -f "/etc/apt/sources.list.d/nodesource.list" ]] && \
    curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - && \
    sudo apt-get install -y nodejs \
    echo "deb https://deb.nodesource.com/node_19.x bionic main" \
        > /etc/apt/sources.list.d/nodesource.list
[[ ! -f "/etc/apt/sources.list.d/yarn.list" ]] && \
    curl -s https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo 'deb https://dl.yarnpkg.com/debian/ stable main' \
        > /etc/apt/sources.list.d/yarn.list
