#!/usr/bin/with-contenv bash

echo "**** installing ros2 dev environment ****"
if ! dpkg -l | grep gnupg > /dev/null; then
    apt-get update && apt-get install -y gnupg
fi

source /etc/lsb-release
if [ ! -f "/etc/apt/sources.list.d/ros2.list" ]; then
    curl -sL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | apt-key add - && \
    echo "deb http://packages.ros.org/ros2/ubuntu ${DISTRIB_CODENAME} main" \
        > /etc/apt/sources.list.d/ros2.list
fi
