#!/usr/bin/with-contenv bash

# Determine if setup is needed
if ! command -v apprise; then
  ## Ubuntu
  if [ -f /usr/bin/apt ]; then
    apt-get update
    apt-get install --no-install-recommends -y \
      python3 \
      python3-pip
  fi
  # Alpine
  if [ -f /sbin/apk ]; then
    apk add --no-cache \
      python3 \
      py3-pip
  fi

  # setuptools
  python3 -m pip install --upgrade pip setuptools

  # apprise
  python3 -m pip install --upgrade apprise

fi
