#!/usr/bin/with-contenv bash

# Determine if setup is needed
if ! command -v apprise; then
  ## Ubuntu
  if [ -f /usr/bin/apt ]; then
    apt-get update
    apt-get install --no-install-recommends -y \
      python3 \
      python3-pip \
      runc
  fi
  # Alpine
  if [ -f /sbin/apk ]; then
    apk add --no-cache \
      cargo \
      libffi-dev \
      openssl-dev \
      python3 \
      python3-dev \
      python3 \
      py3-pip
  fi

  # setuptools
  python3 -m pip install --upgrade pip setuptools

  # apprise
  python3 -m pip install --upgrade apprise

  # cleanup cargo
  rm -rf \
    ${HOME}/.cargo

fi
