#!/usr/bin/with-contenv bash

# Determine if setup is needed
if ! command -v apprise; then
    ## Ubuntu
    if [ -f /usr/bin/apt ]; then
        apt-get install --no-install-recommends -y \
            python3 \
            python3-pip \
            runc
        LINK_DISTRO="ubuntu"
    fi
    # Alpine
    if [ -f /sbin/apk ]; then
        apk add --no-cache \
            cargo \
            libffi-dev \
            openssl-dev \
            python3 \
            python3-dev \
            python3 \
            py3-pip
        LINK_DISTRO="alpine"
    fi

    # setuptools
    python3 -m pip install --upgrade pip setuptools

    # apprise
    python3 -m pip install --upgrade --find-links https://wheel-index.linuxserver.io/${LINK_DISTRO}/ apprise

    # cleanup cargo
    rm -rf \
        ${HOME}/.cargo
fi
