#!/usr/bin/with-contenv bash

echo "*** AWSCLI Installer ***"
echo "Checking if awscli is installed"

if ! aws -v COMMAND &> /dev/null; then 
    echo "awscli not installed, installing now..." 
    if ! pip3 -v COMMAND &> /dev/null; then
        echo "pip3 not installed, installing now..." 
        apt-get install python3 python3-pip -y
    fi
    pip3 install awscli
else
    echo "awscli already installed, skipping!"
fi