#!/usr/bin/with-contenv bash

if [ ! -f /usr/local/bin/docker ]; then
    echo "**** Docker mod not installed, skipping SWAG auto-proxy ****"
    exit 0
fi

rm -rf /etc/nginx/http.d/auto-proxy*.conf /config/nginx/proxy-confs/auto-proxy*.conf
sed -i 's|#include /etc/nginx/http.d|include /etc/nginx/http.d|' /config/nginx/nginx.conf
cp /defaults/auto-proxy-readme /etc/nginx/http.d/auto-proxy-readme
rm -rf /auto-proxy
mkdir /auto-proxy

if ! grep -q "/app/auto-proxy.sh" /config/crontabs/root; then
    echo "*       *       *       *       *       /app/auto-proxy.sh" >> /config/crontabs/root
    cp /config/crontabs/root /etc/crontabs/root
fi

/app/auto-proxy.sh
