#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC2046

conf_file="/config/nginx/cf_real-ip.conf"

curl --connect-timeout 5 --max-time 5 --retry 3 --retry-delay 0 --retry-max-time 20 https://www.cloudflare.com/ips-v4 &> /dev/null

rc=$?

if [[ ${rc} -eq 0 ]]; then
	printf "set_real_ip_from %b;\n" $({
		curl -s "https://www.cloudflare.com/ips-v4" &
		curl -s "https://www.cloudflare.com/ips-v6" &
		ip route | grep -v default | awk '{print $1}'
	}) > ${conf_file}
elif [ ! -f ${conf_file} ]; then
	printf "set_real_ip_from %b;\n" $(ip route | grep -v default | awk '{print $1}') > ${conf_file}
fi

chown abc:abc ${conf_file}
