#!/usr/bin/with-contenv bash

PAR2_VERSION="0.8.1"
PAR2_URL="https://github.com/Parchive/par2cmdline/releases/download/v$PAR2_VERSION/par2cmdline-$PAR2_VERSION.tar.gz"
echo "UPDATED 12/22/22"
echo "NZBGet Essentials FIXED - Installation Started"
apk --update upgrade
echo "Phase 1 - Dependencies are being installed...."
apk add --no-cache \
	tar \
	make \
	g++ \
	ca-certificates \
	wget \
	autoconf \
	automake \
	git \
	build-base
update-ca-certificates
echo "Phase 1 - DONE"
echo " "
echo "Phase 2 - Binaries are being installed..."
apk add --no-cache \
	openssl \
	p7zip \
	unzip
apk add --no-cache --repository https://dl-cdn.alpinelinux.org/alpine/v3.12/main/ \
	unrar \
	python2 \
	ffmpeg
echo "Phase 2 - DONE"
if [ -f /usr/local/bin/par2 ]; then
	echo "`par2 -V` is already installed"
	echo "NZBGet Essentials - Installation Ended"
else
	echo "PAR2 Installation Started"
	mkdir -p /tmp/par2
	curl -kL ${PAR2_URL} | tar -xz -C /tmp/par2 --strip-components=1
	cd /tmp/par2
	aclocal
	automake --add-missing
	autoconf
	./configure -q
	make -s
	make install
	rm -rf /tmp/*
fi
echo " "
echo "NZBGet Essentials - Installation Ended"
