#!/usr/bin/with-contenv bash

PAR2_VERSION="0.8.1"
PAR2_URL="https://github.com/Parchive/par2cmdline/releases/download/v0.8.1/par2cmdline-$PAR2_VERSION.tar.gz"
echo "NZBGet Essentials - Installation Started"
echo http://dl-cdn.alpinelinux.org/alpine/edge/main > /etc/apk/repositories
echo http://dl-cdn.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
apk --update upgrade
echo "Phase 1 - Dependencies are being installed...."
apk add --no-cache --virtual=build-dependencies \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
	tar \
	make \
	g++ \
	ca-certificates \
	wget \
	autoconf \
	automake \
	openmp \
	git \
	build-base
update-ca-certificates
echo "Phase 1 - DONE"
echo " "
echo "Phase 2 - Binaries are being installed..."
apk add --no-cache \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
	ffmpeg \
	openssl \
	p7zip \
	unzip \
	unrar \
	python2
echo "Phase 2 - DONE"
echo " "
if [ -f /usr/local/bin/par2 ]; then
	echo "`par2 -V` is already installed"
	echo "NZBGet Essentials - Installation Ended"
else
	echo "PAR2 Installation Started"
	mkdir -p /tmp/par2
	curl -kL ${PAR2_URL} | tar -xz -C /tmp/par2 --strip-components=1
	cd /tmp/par2
	aclocal
	automake --add-missing
	autoconf
	./configure
	make
	make install
	rm -rf /tmp/*
fi
echo "NZBGet Essentials - Installation Ended"
