#!/usr/bin/with-contenv bash

echo "ensuring golang is in PATH"
if grep -q '^PATH=' /etc/services.d/code-server/run; then
  if ! grep -q '^PATH=.*/usr/local/go/bin.*' /etc/services.d/code-server/run; then
    sed -i '/PATH/ s/$/:\/usr\/local\/go\/bin/' /etc/services.d/code-server/run
  fi
else
  sed -i '/^#!\/usr\/bin/a \\n# Added by codeserver-golang\nexport PATH=$PATH:/usr/local/go/bin' /etc/services.d/code-server/run
fi

ARCH=$(uname -m)
if [ -f "/golang/golang_${ARCH}.tar.gz" ]; then
  echo "Installing golang"
  tar xzf "/golang/golang_${ARCH}.tar.gz" -C /usr/local
  rm -rf /golang
else
  echo "Golang already installed, skipping"
fi
