#!/usr/bin/with-contenv bash

gh_latest() {
  curl -s https://api.github.com/repos/$1/$2/releases/latest \
    | grep "tag_name" \
    | cut -d : -f 2,3 \
    | tr -d '\"\ v,'
}

# replace these with specific versions if needed (i.e 1.7.2 for Julia)
JULIA_VERSION=$(gh_latest julialang julia)

# Julia
wget -q -q https://julialang-s3.julialang.org/bin/linux/x64/`echo ${JULIA_VERSION} | cut -d. -f 1,2`/julia-${JULIA_VERSION}-linux-x86_64.tar.gz
tar fxz julia-${JULIA_VERSION}-linux-x86_64.tar.gz
rm -R julia-${JULIA_VERSION}-linux-x86_64.tar.gz
mv julia-${JULIA_VERSION}/bin/julia /usr/local/bin


# extensions
install-extension julia-vscode.julia-vscode
# latex-input
install-extension yellpika.latex-input
# vscode-format-context-menu
install-extension lacroixdavid1.vscode-format-context-menu
# vscode-julia-formatter
install-extension singularitti.vscode-julia-formatter
# better-toml
install-extension bungcip.better-toml


chown -R root:root /root
chmod -R 600 /root/.ssh
