#!/usr/bin/with-contenv bash

# Determine if setup is needed
if [ ! -f "/usr/bin/apt" ]; then
  echo "**** Image is not Ubuntu, skipping opencl-intel install ****"
  exit 0
fi

pkgs='mesa-vdpau-drivers mesa-va-drivers mesa-vdpau-drivers libdrm-radeon1'

install=false
for pkg in $pkgs; do
  status="$(dpkg-query -W --showformat='${db:Status-Status}' "$pkg" 2>&1)"
  if [ ! $? = 0 ] || [ ! "$status" = installed ]; then
    install=true
    break
  fi
done

if "$install"; then
   echo "**** Installing mesa ****"
   apt-get update

   apt-get install -y \
   gpg

   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F63F0F2B90935439
   echo "deb http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu focal main" > /etc/apt/sources.list.d/kisak-ubuntu-kisak-mesa-bionic.list

   apt-get update

   apt-get install -y $pkgs
fi
