#!/usr/bin/with-contenv bash

echo "**** installing nvm ****"
export NVM_DIR="$HOME/.nvm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

echo "**** loading nvm ****"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# This loads nvm bash_completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

echo "**** installing the current stable LTS release of Node.js ****"
nvm install --lts

echo "**** switching to the current stable LTS release of Node.js  ****"
nvm use --lts

echo "**** installing yarn  ****"
npm install -g yarn

mkdir -p /config/.config
chown -R abc /config/.config
chown -R abc /config/.nvm