#!/usr/bin/with-contenv bash

echo "**** installing python3 dev environment ****"
apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    python3-pip \
    python3-venv
