#!/usr/bin/with-contenv bash

echo "**** installing R dev environment ****"
apt-get install -y --no-install-recommends \
    dirmngr \
    software-properties-common \
    wget

wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"

apt-get install -y \
    build-essential \
    r-base
