#!/usr/bin/with-contenv bash

# Install python3 first
apt-get update && apt-get install -y \
  build-essential \
  libssl-dev \
  libffi-dev \
  python3-dev \
  python3-pip \
  python3-venv

# Install python modules
pip3 install jupyterlab scikit-learn
