#!/usr/bin/with-contenv bash

# Determine if setup is needed
if [ ! -f /usr/local/lib/python***/dist-packages/sshuttle ] && \
[ -f /usr/bin/apt ]; then
  ## Ubuntu
  apt-get update
  apt-get install --no-install-recommends -y \
    iptables \
    openssh-client \
    python3 \
    python3-pip 
  pip3 install sshuttle
fi
if [ ! -f /usr/lib/python***/site-packages/sshuttle ] && \
[ -f /sbin/apk ]; then
  # Alpine
  apk add --no-cache \
    iptables \
    openssh \
    py3-pip \
    python3 
  pip3 install sshuttle
fi

chown -R root:root /root
chmod -R 600 /root/.ssh
