#!/usr/bin/with-contenv bash
APP_FILEPATH='/config/qBittorrent/qBittorrent.conf'
RELEASE_FILEPATH='/vuetorrent/release.json'
NEEDS_UPDATE=false
CURRENT_RELEASE=$(curl -s https://api.github.com/repos/WDaan/VueTorrent/releases/latest | jq -r ".assets[]")

# ===============================================
check_updates() {
    if [[ ! -d ./vuetorrent ]]; then
        NEEDS_UPDATE=true
    elif [[ ! -f $RELEASE_FILEPATH ]]; then
        NEEDS_UPDATE=true
    else
        old_date=$(date -d $(cat "${RELEASE_FILEPATH}" | jq -r ".updated_at") +%s)
        new_date=$(date -d $(echo $CURRENT_RELEASE | jq -r ".updated_at") +%s)
        if [ $new_date -gt $old_date ]; then
            NEEDS_UPDATE=true
        fi
    fi
}
update_ui() {
    printf '\nDownloading qBittorrent webui to "/vuetorrent"..please wait\n'
    curl -L $(echo $CURRENT_RELEASE | jq -r ".browser_download_url") --output /tmp/vuetorrent.zip
    printf '\nDownload finished\n\n'
    if [[ -d /vuetorrent ]]; then
        rm -rf /vuetorrent
    fi
    # mkdir -p /vuetorrent
    unzip -q /tmp/vuetorrent.zip -d /
    echo $CURRENT_RELEASE >"${RELEASE_FILEPATH}"
}
# ===============================================

echo '------------------------------'
echo '| qBittorrent vuetorrent Mod |'
echo '------------------------------'

check_updates

if "$NEEDS_UPDATE" = "true"; then
    echo '---------------------------------------'
    echo '| Downloading WebUI files from github |'
    echo '---------------------------------------'
    update_ui
else
    echo '  WebUI files are up-to-date!'
fi

if ! grep -q "WebUI\\\RootFolder" "${APP_FILEPATH}"; then
    echo '--------------------------------------'
    echo '| Adding WebUI\RootFolder=/vuetorrent |'
    echo '--------------------------------------'
    sed -i -e '$aWebUI\\RootFolder=/vuetorrent' "${APP_FILEPATH}"
fi

if ! grep -q "WebUI\\\AlternativeUIEnabled" "${APP_FILEPATH}"; then
    echo '------------------------------------------'
    echo '| Adding WebUI\AlternativeUIEnabled=true |'
    echo '------------------------------------------'
    sed -i -e '$aWebUI\\AlternativeUIEnabled=true' "${APP_FILEPATH}"
fi

if ! grep -q "WebUI\\\RootFolder=/vuetorrent" "${APP_FILEPATH}" || ! grep -q "WebUI\\\AlternativeUIEnabled=true" "${APP_FILEPATH}"; then
    echo '-------------------------------------------------------'
    echo '| Updating RootFolder and AlternativeUIEnabled values |'
    echo '-------------------------------------------------------'
    sed -i "s/WebUI\\\AlternativeUIEnabled=.*$/WebUI\\\AlternativeUIEnabled=true/g" "${APP_FILEPATH}"
    sed -i "s/WebUI\\\RootFolder=.*$/WebUI\\\RootFolder=\/vuetorrent/g" "${APP_FILEPATH}"
fi
