#!/usr/bin/with-contenv bash

echo "**** installing docker environment ****"
if ! dpkg -l | grep gnupg > /dev/null; then
  apt-get update && apt-get install -y gnupg
fi
[[ ! -f "/etc/apt/sources.list.d/docker-ce.list" ]] && \
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
  source /etc/os-release && \
  echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $UBUNTU_CODENAME stable" > /etc/apt/sources.list.d/docker-ce.list
apt-get update && apt-get install -y --no-install-recommends \
  docker-ce
echo "**** fixing permissions ****"
DOCKER_GID=$(stat -c '%g' "/var/run/docker.sock")
if id -G abc | grep -qw "$DOCKER_GID"; then
  exit 0
else
  DOCKER_NAME=$(getent group "${DOCKER_GID}" | awk -F: '{print $1}')
  if [ -z "${DOCKER_NAME}" ]; then
    DOCKER_NAME="dockergroup"
    groupadd -g "${DOCKER_GID}" "${DOCKER_NAME}"
  fi
  usermod -aG "${DOCKER_NAME}" abc
fi