#!/usr/bin/with-contenv bash

echo "**** installing nodejs dev environment ****"
[[ ! -f "/etc/apt/sources.list.d/nodesource.list" ]] && \
  curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
  echo 'deb https://deb.nodesource.com/node_12.x bionic main' \
    > /etc/apt/sources.list.d/nodesource.list
[[ ! -f "/etc/apt/sources.list.d/yarn.list" ]] && \
  curl -s https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo 'deb https://dl.yarnpkg.com/debian/ stable main' \
    > /etc/apt/sources.list.d/yarn.list
apt-get update && apt-get install -y \
  nodejs \
  yarn
